### ISSUE TITLE
Non-speech descriptions are not filtered out

### ISSUE THREAD

**Issue by tannisroot** [ser/wyoming-whisper-api-client#2]
When running whisper.cpp server, sometimes the audio is transcribed with non-speech descriptions. For example:
![image](https://github.com/user-attachments/assets/de294600-2f50-4ff4-b1c3-8a99f146fbd3)
I am not sure why this is not needed for faster-whisper (custom model?), or maybe it does actually filter these out from the output before sending to Home Assistant, but without filtering these out, this doesn't really work with the default conversation agent.

**Comment by ser** [comment]
I think it's possible to switch it off in whisper server? I am closing this issue as it's not related to the client, it's server thing.

**Comment by tannisroot** [comment]
> I think it's possible to switch it off in whisper server? I am closing this issue as it's not related to the client, it's server thing.

It's not, although there is a variable you can modify in the code, it just replaces non-speech descriptions like the one on the picture with hallucinations, I think it's why it was never properly exposed as an option or even documented.
Honestly i've looked and looked and there was just no way to properly get rid of these in the server itself, which is a shame because it works so much faster thanks to GPU acceleration.
I think filtering based on regex in the api-client itself would make more sense, but of course as the project owner it's up to you whether it's a good idea to have such a feature. I'll just hope this issue is solve in the future in whisper.cpp itself.

**Comment by tannisroot** [comment]
Also, wyoming-whisper-cpp does actually straight up regex BLANK audio out:
wyoming_whisper_cpp/handler.py

**Comment by tannisroot** [comment]
Opps, sorry
https://github.com/rhasspy/wyoming-whisper-cpp/blob/17948c496eb9ccfebd751401b858267fd3e8a177/wyoming_whisper_cpp/handler.py#L92
