### ISSUE TITLE
Arguments not accepted

### ISSUE THREAD

**Issue by StrandmonYellow** [ser/wyoming-whisper-api-client#4]
Hi There,

I am trying to get this working inside a docker container on my nas. I already have whisper.cpp running in a separate container, and this is working fine. I downloaded the project files, made and saved a docker image using the dockerfile in your downloaded files. Now when i want to start the container with the command you provided: 

`` ./script/run --uri tcp://0.0.0.0:7891 --debug --api http://myip:8910/inference`` 

I get this error in the logs: 

``` 
usage: __main__.py [-h] --api API --uri URI [--debug]
[--log-format LOG_FORMAT] [--version]
__main__.py: error: the following arguments are required: --api, --uri 
```

How can i solve this error? I already tried a lot of things. 

Aside from this error, thanks for this amazing tool!! I am really happy if I can get it working :)

**Comment by ser** [comment]
As I do not use docker, maybe the author of that part, @SystemZ,  is able to help you?

**Comment by SystemZ** [comment]
Sure, I'll try to help.

@StrandmonYellow can you provide full cmd which you are using to launch container with and/or docker compose yaml?

**Comment by StrandmonYellow** [comment]
Thanks for the fast reply!

I am quite new docker with little experience, so correct me if I say something stupid :)

I started by downloading the project files, and as said above created a docker image and saved it locally. Then I uploaded the image to my Ugreen Nas, where I could create a container with the image. I only use docker (run?) and not docker compose. 

I used the above mentioned startup command to start the docker container. Below is my configuration in the Ugreen UGOS Docker application. 

![image](https://github.com/user-attachments/assets/48faafbe-a1e0-4835-ab66-d7faeb18b418)

This is the only command I give it to start the container. 

I could also start a container using docker compose with a yaml file, but I don't know how to implement it this way or what should be in the yaml file. 

![image](https://github.com/user-attachments/assets/e8cd8827-14d3-478f-a593-3505dbd17da3)

**Comment by StrandmonYellow** [comment]
I now have both containers running with the following yaml compose file:

```
services:
  whisper-server:
    image: ghcr.io/ggerganov/whisper.cpp:main
    container_name: whisper.cpp_server-compose
    ports:
      - "8910:8910"  # Exposing the Whisper server on port 8910
    volumes:
      - /volume1/docker/whisper/models:/app/models  # Mount model files if needed
    command: >
      ./server -m /app/models/ggml-base.en.bin
      --host 0.0.0.0 --port 8910
      --print-realtime --print-progress
      --model /app/models/ggml-base.en.bin
      --convert

  wyoming-whisper-client:
    image: wyoming-whisper-client  # The Wyoming Whisper API client image
    container_name: wyoming_whisper_client-compose
    ports:
    - "7891:7891"  # Exposing the Wyoming API client on port 7891
    depends_on:
    - whisper-server  # Ensures the whisper-server starts before this service
    command: >
      --uri tcp://0.0.0.0:7891
      --api http://whisper-server:8910/inference
      --debug
```

I can connect it to home assistant, and in the logs i can see that the audio starts steaming. But then i get an error:

``ERROR:asyncio:Task exception was never retrieved`` 

and:

``wyoming_whisper_client-compose  | DEBUG:httpcore.connection:connect_tcp.failed exception=ConnectError(OSError('All connection attempts failed'))``

Tomorrow I will look into it further.

**Comment by StrandmonYellow** [comment]
Okay for everyone that is also having issues, i fixed it the following way. 

I made some mistakes in my yaml compose file (namings not being correct). 

I noticed that when I started the whisper server manually, then it did work. So the whisper server was not actually listening on port 8910. I found out that the "command" function did not work for me. It does not overwrite any default values that are already set. After trying and searching a lot i found out it worked by using the "entrypoint" command. This overwrites any defaults that are already set inside the image. The complete yaml file can be seen below:

```
services:
  whisper-server:
    image: ghcr.io/ggerganov/whisper.cpp:main
    container_name: whisper-server-compose
    ports:
      - "8910:8910"  # Exposing the Whisper server on port 8910
    volumes:
      - /volume1/docker/whisper/models:/app/models  # Mount model files
    entrypoint: >
      ./server -m /app/models/ggml-base.bin
      --host 0.0.0.0 --port 8910
      --print-realtime --print-progress

  wyoming-whisper-client:
    image: wyoming-whisper-client  # The Wyoming Whisper API client image
    container_name: wyoming_whisper_client-compose
    ports:
      - "7891:7891"  # Exposing the Wyoming API client on port 7891 for Home Assistant
    command: >
      --uri tcp://0.0.0.0:7891
      --api http://whisper-server-compose:8910/inference
      --debug
```

**Comment by thiswillbeyourgithub** [comment]
Hi everyone. I've been struggling to get this all working with [faster-whisper-server](https://github.com/fedirz/faster-whisper-server) as I'm already running a whisper instance for [open-webui](https://github.com/open-webui/open-webui/) and wanted to reuse the same model with home assistant without duplicating instances etc.


Here's what I ended up doing:

First clone this repo, then cd into it.

Create a docker-compose.yaml file with the following content:
```yaml

services:
  wyoming-whisper-api-client:
    container_name: wyoming_to_whisper
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7891:7891"
    restart: unless-stopped
    command: >
      --uri tcp://0.0.0.0:7891
      --api http://0.0.0.0:8001/v1/audio/transcriptions
      --debug
    # The --uri points to this container
    # The --api points to the faster whisper server. In my case the port used on the faster whisper server container is 8001
    network_mode: host  # this is needed to connect to my faster-whisper-container, same computer but difference compose so I use the host network
```

I huge thank you to @ser for making this repo. I'm utterly surprised that there's not more people that already have a whisper instance running when they get into home assistant stuff.


Also @StrandmonYellow  I cannot recommend enough using LLMs to teach one's self how to use docker etc. I started alone from nothing and now am regretting not starting sooner!

**Comment by ser** [comment]
I am pretty unsure if faster-whisper API is compatible with whisper API.

**Comment by thiswillbeyourgithub** [comment]
Pretty sure it is. But in any case faster whisper **server** definitely is whisper compliant

**Comment by ser** [comment]
if it is, why do you use
```
--api http://0.0.0.0:8001/v1/audio/transcriptions
```
instead of
```
--api http://whisper-server:8910/inference
```
?

**Comment by thiswillbeyourgithub** [comment]
The endpoint differs but the api is the same. It spits out the same kind lf dict.

And by whisper compliant I mean compliant with the original / reference implementation by openai, which for historical reason whispercpp does not stricrly follow.
